version: '3.4'

services:
  ioutility.adm.apresentacao.service:
    image: ioutility.adm.apresentacao.service
    ports:
      - '8089:80'

  ioutility.apigateway.service:
    image: ioutility.apigateway.service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5022:80"
  
  ioutility.storage.service:
    image: ioutility.storage.service
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5041:80"
    depends_on:
      - ioutility.rabbitmq

  ioutility.cadastro.service:
    image: iotuility.cadastro.service
    hostname: iotuility.cadastro.service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - 80
    depends_on:
      - ioutility.sqlserver
      - ioutility.rabbitmq
    restart: on-failure

  ioutility.rabbitmq:
    image: rabbitmq:3-management
    hostname: ioutilityrabbitmq
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'
      - '15671:15671'
      - '15672:15672'

  ioutility.sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: ioutilitycadastrodbserver
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: Express
    ports:
      - '1433:1433'
    volumes:
      -  C:\dados\valumes\mssql:/var/opt/mssql3

# docker-compose  -f "ioutility-compose.yml"   -p ioutilitycompose --ansi never up -d